webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField, DateField
from wtforms.validators import DataRequired, Email, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw = {'class': 'form-check-input'})
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-primary"})

class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    email = StringField('Электронная почта', validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    password2 = PasswordField('Пароль', validators=[DataRequired(), EqualTo('password')], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-primary"})

class EditCalendarEventForm(FlaskForm):
    event_start = DateField('Начало', format="%Y-%m-%d", validators=[DataRequired()])
    event_end = DateField('Конец', format="%Y-%m-%d", validators=[DataRequired()])
    submit = SubmitField('Подтвердить', render_kw={"class":"btn btn-light"})

webapp/user/views.py
from flask import Blueprint, Flask, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user
from webapp.user.forms import LoginForm, RegistrationForm
from models import User
from webapp.db import db

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.start'))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)

@blueprint.route('/process-login', methods = ['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username==form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно вошли на сайт')
            return redirect(url_for('main_page.start'))
        
    flash('Неправильные имя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('main_page.start'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.start'))
    title = "Регистрация"
    registration_form = RegistrationForm()
    return render_template("user/registration.html", page_title=title, form=registration_form)

@blueprint.route('/process-reg', methods = ['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role='user')
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash('Вы успешно зарегистрированы')
        return redirect(url_for('user.login'))
    flash('Пожалуйста исправьте ошибки')
    return redirect(url_for('user.register'))

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <div class = "row">
        <div class = "col-4">       <!-- Размер горизонтальной строки--->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                       {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form action = "{{ url_for('user.process_login') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }} <br>
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}  <br>
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_='form-check-label') }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class = "col-8">           <!-- Размер горизонтальной строки--->
        
        </div>
    </div>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <div class = "row">
        <div class = "col-4">       <!-- Размер горизонтальной строки--->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                       {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <form action = "{{ url_for('user.process_reg') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }} <br>
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.email.label }} <br>
                    {{ form.email() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}  <br>
                    {{ form.password() }}
                </div>
                <div class="form-group">
                    {{ form.password2.label }}  <br>
                    {{ form.password2() }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class = "col-8">           <!-- Размер горизонтальной строки--->
        
        </div>
    </div>
{% endblock %}

webapp/templates/user/unauthenticated.html
{% extends "base.html" %}

{% block content %}
    <div class = "row">
        <div class = "col-6">       <!-- Размер горизонтальной строки--->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                       {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class = "row">
        <div class = "col-6">
            <h2 >Сервис доступен только зарегистрированным пользователям</h2>
        </div>
    </div> 
    <div class = "row ">
        <div class="pt-lg-3">
            <div class = "col-6">
                <form action = "{{ url_for('user.login') }}" >
                    <input class="btn btn-light" type="submit" value="Войти">
                </form>
            </div>
        </div>
    </div>
    <div class="pt-lg-3">
        <div class = "row">
            <div class = "col-6">
                <form action = "{{ url_for('user.register') }}" >
                    <input class="btn btn-light" type="submit" value="Зарегистрироваться">
                </form>
            </div>    
        </div>
    </div>
{% endblock %}