webapp/main_page/views.py
import os
from flask import Blueprint, current_app, render_template, Flask, flash, request, redirect, url_for
import matplotlib.pyplot as plt
from webapp.user.decorators import user_required
from webapp.config import ALLOWED_EXTENSIONS, UPLOAD_FOLDER 
from get_orders_table import delete_orders_data
from get_plots_and_tables import get_analysed_data
from normalise_users_data import normalise_users_data
from normalise_orders_data import normalise_orders_data
from load_clients import read_csv, save_clients
from load_orders import read_csv as read_csv_orders
from load_orders import save_orders
from load_expences import read_csv as read_csv_expences
from load_expences import save_expenses
from flask_login import current_user
from webapp.user.forms import EditCalendarEventForm

blueprint = Blueprint('main_page', __name__)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def add_file(file, name, flag):
    if file and allowed_file(file.filename):
        filename = name
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        flag += 1
    return flag


@blueprint.route('/')
@user_required
def start():
    return render_template("main/start_page.html")


@blueprint.route('/data_analysis_add_data')
@user_required
def data_analysis_add_data():
    current_user_id = current_user.get_id()
    print(current_user.get_id())
    normalise_users_data(current_user_id)
    clients_data = read_csv('normalised_clients.csv')
    save_clients(clients_data)
    normalise_orders_data()
    orders_data = read_csv_orders('normalised_orders.csv')
    save_orders(orders_data, current_user_id)
    expenses_data = read_csv_expences('fake_expences.csv', current_user_id)
    save_expenses(expenses_data)
    return render_template("main/data_analysis.html")


@blueprint.route('/data_analysis/<string:period>')
@user_required
def data_analysis(period):
    if period == 'Y' or period == 'M' or period == 'D':
        current_user_id = current_user.get_id()
        try:
            table=get_analysed_data(period, current_user_id)
        except ValueError:
            flash('У вас нет записей в базе данных, добавьте файлы чтобы проанализировать данные')
            return render_template("main/index.html", page_title="Подгрузите файлы", flag=0)
        table_columns = table.columns.values.tolist()
        table_values = table.values.astype(float).tolist()
        dates = table.index.values.astype(str).tolist()
        if period == 'Y':
            table_columns.insert(0, "Год")
            image_hidden = False
        elif period == 'M':
            table.plot(figsize=(10,10), subplots=True)
            plt.savefig(os.path.join('webapp/static/', 'my_plot.jpg'))
            table_columns.insert(0, "Месяц")
            image_hidden = True
        elif period == 'D':
            table.plot(figsize=(10,10), subplots=True)
            plt.savefig(os.path.join('webapp/static/', 'my_plot.jpg'))
            table_columns.insert(0, "День")
            image_hidden = True
        for i in range(len(table_values)):
            table_values[i][:-1] = [round(elem) for elem in table_values[i][:-1]]
            table_values[i][-1] = format(table_values[i][-1], '.2f')
            table_values[i].insert(0, dates[i])
            range_hidden = False
        return render_template("main/data_analysis.html", table_columns=table_columns, table_values=table_values, range_hidden=range_hidden, image_hidden=image_hidden)
    elif period == 'R':
        range_hidden = True
        allowed_dates = EditCalendarEventForm()
        return render_template("main/data_analysis.html", range_hidden=range_hidden, form=allowed_dates)
    return render_template("main/data_analysis.html")  
    

@blueprint.route('/data_analysis_range', methods = ['POST'])
@user_required
def data_analysis_range():
    allowed_dates = EditCalendarEventForm()
    current_user_id = current_user.get_id()
    try:
        table=get_analysed_data('D', current_user_id)
    except ValueError:
        flash('У вас нет записей в базе данных, добавьте файлы чтобы проанализировать данные') 
        return render_template("main/index.html", page_title="Подгрузите файлы", flag=0)
    dates = table.index.values.astype('datetime64[D]').tolist()
    if allowed_dates.event_start.data <= allowed_dates.event_end.data:
        for date_index in dates:
            if date_index < allowed_dates.event_start.data or date_index > allowed_dates.event_end.data:
                date_index_str = date_index.strftime('%Y-%m-%d')
                table = table.drop(date_index_str)
        table_columns = table.columns.values.tolist()
        table_values = table.values.astype(float).tolist()
        dates = table.index.values.astype(str).tolist()
        table.plot(figsize=(10,10), subplots=True)
        plt.savefig(os.path.join('webapp/static/', 'my_plot.jpg'))
        table_columns.insert(0, "День")
        image_hidden = True
        for i in range(len(table_values)):
            table_values[i][:-1] = [round(elem) for elem in table_values[i][:-1]]
            table_values[i][-1] = format(table_values[i][-1], '.2f')
            table_values[i].insert(0, dates[i])
        return render_template("main/data_analysis.html", table_columns=table_columns, table_values=table_values, image_hidden=image_hidden)
    else:
        flash('Некорректно указан диапазон')
        return render_template("main/data_analysis.html") 


@blueprint.route('/add_files/<int:delete>', methods=['GET', 'POST'])
@user_required
def upload_file(delete=0):
    if delete == 1:
        current_user_id = current_user.get_id()
        try:
            delete_orders_data(current_user_id)
            flash('Записи в базе данных удалены')
        except ValueError:
            flash('У вас нет записей в базе данных') 
    flag = 0
    if request.method == 'POST':
        if 'file_1' not in request.files or 'file_2' not in request.files or 'file_3' not in request.files:
            flash('Недопустимый формат файла')
            return redirect(request.url)
        file_users = request.files['file_1']
        file_orders = request.files['file_2']
        file_expences = request.files['file_3']        
        if file_users.filename == '' and file_orders.filename == '' and file_expences.filename == '':
            flash('Файлы не добавлены')
            return redirect(request.url)
        flag = add_file(file_users, "fake_clients.csv", flag)
        flag = add_file(file_orders, "fake_orders.csv", flag)
        flag = add_file(file_expences, "fake_expences.csv", flag)    
    return render_template("main/index.html", page_title="Подгрузите файлы", flag=flag)

webapp/templates/main/data_analysis.html
{% extends "base.html" %}

{% block content %}

<div class = "row">
    <div class = "col-12">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                   {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        <h1 class="text-center">{{ page_title }}</h1>
    </div>
</div> 
<div class = "row">
    <div class = "col-12">
        <h1 class="text-center">Анализ данных</h1>
    </div>    
</div>
<div class = "row justify-content-center">
    <div class = "col-3">
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Выберите период
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{{ url_for('main_page.data_analysis', period='Y') }}">Год</a>
                <a class="dropdown-item" href="{{ url_for('main_page.data_analysis', period='M') }}">Месяц</a>
                <a class="dropdown-item" href="{{ url_for('main_page.data_analysis', period='D') }}">День</a>
                <a class="dropdown-item" href="{{ url_for('main_page.data_analysis', period='R') }}">В диапазоне</a>
            </div>
        </div>
    </div>
    {% if range_hidden %} 
    <form action = "{{ url_for('main_page.data_analysis_range') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class = "col-3">
            <div class="form-group">
                {{ form.event_start.label }}
                {{ form.event_start() }}
            </div>
        </div>
        <div class = "col-3">
            <div class="form-group">
                {{ form.event_end.label }}  <br>
                {{ form.event_end() }}
            </div>
        </div>
        <div class = "col-3">
            {{ form.submit() }}
        </div>
    </form>
    {% endif %}
</div>
<style type="text/css">
    table {
    width: 100%;
    border: 1px solid grey;
    }
    /* границы ячеек первого ряда таблицы */
    th {
    border: 1px solid grey;
    }
    /* границы ячеек тела таблицы */
    td {
    border: 1px solid grey;
    }
</style> 
<div class='d-flex justify-content-center'>
<div class = "row">
    <div class = "col-12">
        <table>
            <thead>
                <tr ALIGN=center>
                    {% for column in table_columns %}
                      <th>{{ column }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for values in table_values %}
                    <tr>
                        {% for value in values %}    
                            <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
  </div>
</div>
</div>
{% if image_hidden %}
<div class='d-flex justify-content-center'>
<div class = "row">
    <div class = "col-10">
        <img src="{{ url_for('static', filename='my_plot.jpg') }}" width=900>
        </img>
    </div>
</div>
</div>
{% endif %}


{% endblock %}

webapp/templates/main/index.html
{% extends "base.html" %}

{% block content %}

    <div class = "row">
        <div class = "col-12">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                       {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
            <h1 class="text-center">{{ page_title }}</h1>
        </div>
    </div> 
    <form method=post enctype=multipart/form-data>
    <div class = "row">
        <div class = "col-4">
            <div class="mb-3">
                <h3 class="text-left">Добавьте файл клиентов</h3>
                <input type=file class="btn btn-light" name=file_1>
            </div>
        </div>
        <div class = "col-4">
            <div class="float-right">
                <h3>Добавьте файл заказов</h3>
                <input type=file class="btn btn-light" name=file_2>
            </div>
        </div>
        <div class = "col-4">
            <div class="float-right">
                <h3>Добавьте файл расходов</h3>
                <input type=file class="btn btn-light" name=file_3>
            </div>
        </div>
    </div>
    <div class = "row">
        <div class = "col-12">
            <div class="text-center">
                    <input type=submit class="btn btn-light btn-lg" value=Добавить>
                    {% if flag==3 %}
                        <a class="btn btn-light btn-lg" href="{{ url_for('main_page.data_analysis_add_data') }}" role="button">Проанализировать</a>
                    {% endif %}
            </div>
        </div>
    </div>
    </form>
{% endblock %}

webapp/templates/main/start_page.html
{% extends "base.html" %}

{% block content %}
    <div class = "row">
        <div class = "col-6">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                       {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class = "row">
        <div class = "col-6">
            <h2 >Выберите дальнейшее действие</h2>
        </div>
    </div> 
    <div class = "row ">
        <div class="pt-lg-3">
            <div class = "col-6">
                <form action = "{{ url_for('main_page.upload_file', delete=0) }}" >
                    <input class="btn btn-light" type="submit" value="Добавить файлы">
                </form>
            </div>
        </div>
    </div>
    <div class="pt-lg-3">
        <div class = "row">
            <div class = "col-6">
                <form action = "{{ url_for('main_page.data_analysis', period=' ') }}" >
                    <input class="btn btn-light" type="submit" value="Проанализировать данные из базы">
                </form>
            </div>    
        </div>
    </div>
    <div class="pt-lg-3">
        <div class = "row">
            <div class = "col-6">
                <form action = "{{  url_for('main_page.upload_file', delete=1) }}" >
                    <input class="btn btn-light" type="submit" value="Очистить базу данных">
                </form>
            </div>    
        </div>
    </div>
{% endblock %}